server:
  port: 8062

spring:
  cassandra:
    keyspace-name: ox_bag_tests
    contact-points: localhost
    port: 9042
    username: user
    password: 1234
    schema-action: recreate
    local-datacenter: datacenter1