server:
  port: 8060

spring:
  application:
    name: ox-bag
  cassandra:
    keyspace-name: ox_bag
    contact-points: localhost
    port: 9042
    username: user
    password: 1234
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: datacenter1
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: order-xpress-login
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/order-xpress
            user-name-attribute: principal_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/order-xpress

springdoc:
  swagger-ui.path: /swagger-ui-custom.html
  swagger-ui:
    operationsSorter: method

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      ox-user-get:
        minimum-number-of-calls: 3
        slow-call-duration-threshold: PT1S
      ox-clothes-get:
        minimum-number-of-calls: 5
        slow-call-duration-threshold: PT2S