server:
  port: 8085

spring:
  application:
    name: ox-user
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ox_user
    password: 1234
    url: jdbc:postgresql://localhost:5432/ox_user
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      data-locations:
        - classpath*:/scripts/schema.sql
        - classpath*:/scripts/data.sql

springdoc:
  swagger-ui.path: /swagger-ui-custom.html
  swagger-ui:
    operationsSorter: method

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

mapstruct:
  processor:
    default-component-model: spring

resilience4j:
  circuitbreaker:
    instances:
      ox-bag-create:
        minimum-number-of-calls: 3
        slow-call-duration-threshold:
          seconds: 1
      ox-account-create:
        minimum-number-of-calls: 3
        slow-call-duration-threshold:
          seconds: 1